#! /bin/bash
### BEGIN INIT INFO
# Provides:         rocket-gpu-fallback
# Required-Start:   $remote_fs $syslog update-graphics
# Required-Stop:
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: GPU fallback on NV/AMD
# Description:       Detect unsupported old GPUs and use a suitable driver for them
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start () {
 # check for ATI cards not supported by fglrx
 # all ATI cards (even Apple derivs) have ATI PCI ID 1002, and VGA cards have class 0300h
 detected_radeons=`lspci -n | grep " 0300: " | cut -f3 -d' ' | grep ^1002 | tr '[:lower:]' '[:upper:]'`
 # the fglrx module maintains a list of exact supported cards, extract it
 supported_radeons=`modinfo fglrx | grep alias | sed 's/.*pci:v0000\([0-9A-F][0-9A-F][0-9A-F][0-9A-F]\)d0000\([0-9A-F][0-9A-F][0-9A-F][0-9A-F]\).*/\1:\2/'`
 # set a flag to indicate no supported radeon found
 foundsupportedaticard="false"
 for i in $detected_radeons
 do
   if [[ $supported_radeons == *"$i"* ]]
     then foundsupportedaticard="true"
   fi
 done

 # check for NVIDIA cards not supported by nvidia-glx
 # all NVIDIA cards (even Apple derivs) have NVIDIA PCI ID 10DE, and VGA cards have class 0300h
 detected_geforce=`lspci -n | grep " 0300: " | cut -f3 -d' ' | grep ^10de | tr '[:lower:]' '[:upper:]'`
 # the nvidia driver bundles a list of supported cards
 supported_geforce=`sed -re 's/^.{4}/&:/' /usr/lib/nvidia/current/nvidia.ids`
 # set a flag to indicate no supported geforce found
 foundsupportedgeforcecard="false"
 for i in $detected_geforce
 do
   if [[ $supported_geforce == *"$i"* ]]
     then foundsupportedgeforcecard="true"
   fi
 done

 if [ "x$foundsupportedaticard" == "xfalse" ] && [ "x$foundsupportedgeforcecard" == "xfalse" ]
   then update-alternatives --set glx /usr/lib/mesa-diverted
   mkdir -p /etc/X11/xorg.conf.d
   if [ -n "$detected_geforce" ]
     then update-alternatives --set nvidia /usr/lib/nvidia/legacy-340xx
     update-alternatives --set glx /usr/lib/nvidia
     modprobe nvidia-legacy-340xx
   else
     update-alternatives --set nvidia /usr/lib/nvidia/current
   fi
   if [ -n "$detected_radeons" ]
     then modprobe radeon
   fi
 else
   update-alternatives --set nvidia /usr/lib/nvidia/current
 fi

 ldconfig

 # clear any potential feedback we might have left on screen
 plymouth display-message --text=""
 return 0
}

do_status () {
 return 0
}

case "$1" in
  start|"")
 do_start
 ;;
  restart|reload|force-reload)
 echo "Error: argument '$1' not supported" >&2
 exit 3
 ;;
  stop)
 # No-op
 ;;
  status)
 do_status
 exit $?
 ;;
  *)
 echo "Usage: rocket-fallback-to-mesa" >&2
 exit 3
 ;;
esac

:

